kind: ConfigMap
apiVersion: v1
metadata:
  name: admin-server
data:
  application.yml: |-
    server:
      port: 8080
    management:
      endpoint:
        health:
          enabled: true
        info:
          enabled: true
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              group: ca.zhoozhoo.spring.cloud
    eureka:
      client:
        enabled: false
